# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  maven_test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: src/Test/Java/fr.univavignon.pokedex.api

workflows:
  maven_test:
    jobs:
     - maven_test
