on:
  push

jobs:
  boc_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: doc
        run: mvn -B -f "${{ github.repository }}" javadoc::javadoc
      - name: page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SA_MERE }}
          publish_dir: ./public